### ISSUE TITLE
login?

### ISSUE THREAD

**Issue by steffanjensen** [sudoguy/tiktok_bot#3]
I see you wrote fix me under login, is login still under development ?

Best regards,

Steffan

**Comment by reliefs** [comment]
used this
login_with_email

Got this error:
data=LoginErrorData(captcha='', description='You are visiting our service too frequently.', error_code=7) message='error'

**Comment by reliefs** [comment]
look like we need to solve captcha..

**Comment by reliefs** [comment]
hi sorry to bother you, anything new ?

**Comment by rever96** [comment]
I got your same error, then I logged out from my device, and rerun the code, it works!

**Comment by reliefs** [comment]
wow gonna try that thanks

**Comment by reliefs** [comment]
Now i get this one
description":"Verification code error, please re-enter the verification code.","error_code":1102},"message":"error"

any way to get around that ?

**Comment by rever96** [comment]
You should create account using email/password, the phone number works too, (facebook and others will not in my opinion, because of OAUTH2) then in your device logged in you have to insert your email and pass the verification number test. After that, u log out from device and run the py function

**Comment by reliefs** [comment]
thanks worked like a charm :) Good i will start working on the follow/like/comment/visit profiles functions..

Also scrape stories from ig to tiktok is a function i already have the entire backend for ig scraping. 
Most likely i will implement tensorflow for face detection in my version :)

**Comment by rever96** [comment]
If u need some help implementing follow function and other, ask me without
any regards.

**Comment by reliefs** [comment]
hi i just got logged in, but now i start to get this error again

2019-11-17 19:55:02.722 | DEBUG    | tiktok_bot.client.client:post:70 - Response return status_code: 200, body: {"data":{"captcha":"","description":"You are visiting our service too frequently.","error_code":7},"message":"error"}


I tried to both login and out of the app ? also cleared cache in app. I also went into "logged in device" and logged the api device out.

**Comment by rever96** [comment]
Now I'm getting the same error... When I tried to login on my smartphone it asked the puzzle like captcha, and still getting the error about "too frequently". Probably it's a time related issue about using that access method. I'll launch again the login_email function tomorrow.

**Comment by rever96** [comment]
@reliefs https://github.com/LCSP/tiktokapi-security you have to watch there, maybe would solve our login problem.

**Comment by reliefs** [comment]
yes they are generated here
https://github.com/sudoguy/tiktok_bot/blob/master/tiktok_bot/client/utils.py

They all look unique generated.. but you are most likely right

**Comment by reliefs** [comment]
this is maybe also related

https://github.com/szdc/tiktok-api/issues/115

**Comment by sudoguy** [comment]
@reliefs @rever96
Hey guys, sorry for the late response.
Actually, I have some problems with generating device_id and iid. Right now, these parameters are hardcoded [here, in config.py](https://github.com/sudoguy/tiktok_bot/blob/master/tiktok_bot/api/config.py). That's why you got errors.
And also, we need to send X-Gorgon and X-Chronos in headers. But I do not know how

**Comment by reliefs** [comment]
kk now i am just guessing, so because the iid was used once on the account, the account get blocked the second time ?

Tried a few other iid from internettet, they did not work, gonna keep trying :)

**Comment by raien** [comment]
so , how to resolve this error , body: {"data":{"captcha":"","description":"You are visiting our service too frequently.","error_code":7},"message":"error"},   please help me .

**Comment by elliotalderson-py** [comment]
Same problem here :(

**Comment by reliefs** [comment]
make a new account, logout of app.. and use the bot then it will work..

But only one time :) Then you will start to get error again.

**Comment by sssssppppp** [comment]
take a look at com.ttnet.org.chromium.net.impl.CronetUrlRequest.addSecurityFactor

**Comment by raien** [comment]
@reliefs  why get error again . because Generating anti spam parameters ?

**Comment by reliefs** [comment]
> @reliefs @rever96
> Hey guys, sorry for the late response.
> Actually, I have some problems with generating device_id and iid. Right now, these parameters are hardcoded [here, in config.py](https://github.com/sudoguy/tiktok_bot/blob/master/tiktok_bot/api/config.py). That's why you got errors.
> And also, we need to send X-Gorgon and X-Chronos in headers. But I do not know how

@raien

**Comment by raien** [comment]
@reliefs  thanks ,  so , we can do this . 

const signURL = async (url, ts, deviceId) => {
  const as = 'anti-spam parameter 1';
  const cp = 'anti-spam parameter 2'
  const mas = 'anti-spam parameter 3';
  return `${url}&as=${as}&cp=${cp}&mas=${mas}`;
}

// Required - device parameters
// You need to source these using a man-in-the-middle proxy such as mitmproxy,
// CharlesProxy or PacketCapture (Android)
const params = getRequestParams({
  device_id: '<device_id>',
  fp: '<device_fingerprint>',
  iid: '<install_id>',
  openudid: '<device_open_udid>',
});

generating as,cp,mas device_id,fp,iid,openudid,  And also, we need to send X-Gorgon and X-Chronos in headers ?  To ensure that the API calls normally ？

**Comment by Abdulsamipy** [comment]
> wow gonna try that thanks

can you guide me on how i can install the bot ..i've extracted via pip but can you tell what to do next? ive tried to run bot.py ... but no response

**Comment by reliefs** [comment]
this is not related to this issue..

**Comment by Abdulsamipy** [comment]
> this is not related to this issue..

You're able to run the program?

**Comment by reliefs** [comment]
this is not related to this issue. If you have problems with python read the python documentation.

**Comment by Abdulsamipy** [comment]
i'm getting this error, he account is new and i've logged out from Tiktok too 

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\httpx\concurrency\asyncio.py", line 267, in open_tcp_stream
    stream_reader, stream_writer = await asyncio.wait_for(  # type: ignore
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by rever96** [comment]
that's still not related with this issue...
anyway, that error doesn't seem to be related with that library tho.
Are u sure to have properly installed python3?

**Comment by Abdulsamipy** [comment]
Yes i've installed the it correctly.. my using python via Sublime text 3

**Comment by reliefs** [comment]
can we get him blocked?

**Comment by NmC** [comment]
I am watching repo for a while to track recent tiktok changes. Pls block him, its annoying, he updated all issues with his "install and run" comments :/
Btw his nick Abdulsami **py** 😄

**Comment by raien** [comment]
@reliefs reliefs      tiktok （international) version not X-Gorgon and X-Chronos in headers.

**Comment by reliefs** [comment]
> @reliefs reliefs tiktok （international) version not X-Gorgon and X-Chronos in headers.

@sudoguy

**Comment by reliefs** [comment]
tiktok app is blocked on genymotion linux, but works on bluestacks windows. So takes 5 min to make emulator bot.. but i use lnux as main.. sorry off topic but any way around ? We could just use pytogui.

**Comment by reliefs** [comment]
i have made this auto macro with image detection so we can test limits.
https://github.com/reliefs/tiktokbot

**Comment by HeisSuperHan** [comment]
> @reliefs @ rever96大家好
> ，很抱歉收到您的回复。
> 实际上，在生成device_id和iid时遇到一些问题。现在，这些参数在[此处](https://github.com/sudoguy/tiktok_bot/blob/master/tiktok_bot/api/config.py)被硬编码[在config.py中](https://github.com/sudoguy/tiktok_bot/blob/master/tiktok_bot/api/config.py)。这就是为什么您会出错。
> 而且，我们需要在标头中发送X-Gorgon和X-Chronos。但是我不知道怎么做

hello,i see Tiktracker is complete the login problem , maybe we can Reverse cracking the Tiktracker, this app's can be search on App Store anf Apkpure.com. Thank you

**Comment by reliefs** [comment]
i still think it's the captch ? Because when new user made -> captcha done first login -> bot works on first login ?

**Comment by reliefs** [comment]
video + without watermark is pretty easy to do also get other data.. just did wget tiktok url.. and all data was,

**Comment by reliefs** [comment]
I created this web api with no need for login
https://github.com/reliefs/tiktok-api

Are still working on trying to get login to work :/

**Comment by HeisSuperHan** [comment]
@reliefs  hello,can you complete it ? it's interesting!

**Comment by reliefs** [comment]
sure you can just open an issue what you want migrated here:
https://github.com/instabotai/tiktok-api/issues

I really want these functions intergrated with tiktok_bot if login gets working, is this project abandoned ? Sudoguy is a pretty good dev.

**Comment by reliefs** [comment]
https://mpsocial.com/t/just-signed-up-for-autotokker-com/92890/46

**Comment by reliefs** [comment]
Some stats:

I got up to 2 mill local views in 14 days.. Got pretty famous my country is 6 mill. But today i got banned. 
They not even banned the account, but also the phone.

So far i have not been able to get my account back :/ But I managed to get the phone to work by again with the frameworks by deleting the app and download another version from apkpure.

I will keep you guys updates.

**Comment by Abdulsamipy** [comment]
hi, guys .. does anyone knows how to solve this error ..i've tried creating a new account and logging out of it from my device ... but no luck
`""description":"Verification code error, please re-enter the verification code.","error_code":1102},"message":"error"}`

**Comment by NeelDroid** [comment]
> Some stats:
> 
> I got up to 2 mill local views in 14 days.. Got pretty famous my country is 6 mill. But today i got banned. (Got around 10/30 messages daily, videos from range 270k-15k normal.
> 50/70 concurrent viewers most times i stream on livestream / 37k likes on videos in 14 days)
> They not even banned the account, but also the phone.
> 
> So far i have not been able to get my account back :/ But I managed to get the phone to work again with the frameworks by deleting the app and download another version from apkpure.
> 
> I will keep you guys updated.
> 
> Most likely it was my own premade bots because they was pretty powerful or it was because or signed up for the extra botting service like autotok.
> 
> So I made them take care of unfollow/follow while I made bots for all other tasks. (See my scripts)
> 
> I hope to duplicate it all again :/ But with a mother -> child account at this point.

You are crawling tikitoks.com right? so no hopes left to use tiktok?

**Comment by NeelDroid** [comment]
> sure you can just open an issue what you want migrated here:
> https://github.com/instabotai/tiktok-api/issues
> 
> I really want these functions intergrated with tiktok_bot if login gets working, is this project abandoned ? @sudoguy is a pretty good dev.
> 
> **Right now i have:**
> 
> * get_home_page
> * get_video_homepage
> * get_likes_count
> * get_comment_count
> * get_meta_title
> 
> **I will soon also have:**
> 
> * get_media_url
> * get media hashtags
> 
> It took me around 4-7 hours to make. But better than 90% out there on github :/

You are crawling tikitoks.com right? so no hopes left to use tiktok?

**Comment by steffanjensen** [comment]
sure should not be that hard to make.. but i will not the risk for reward is not there..
